apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-pod
  name: web-pod
  namespace: dev
spec:
  containers:
    - image: nginx
      name: web-pod
      ports:
        - containerPort: 80
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    name: web-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80